require 'uri'
require 'net/http'
require 'openssl'
require 'json'
require 'colorize'
require 'pry'

require_relative '../lib/cli'
require_relative '../lib/madlib1'
require_relative '../lib/madlib2'
require_relative '../lib/madlib3'
require_relative '../lib/api'
require_relative '../secrets'